### ISSUE TITLE
Example wanted: Post Solr schema after creating new multidev env with Drupal

### ISSUE THREAD

**Issue by DavidHernandez** [pantheon-systems/quicksilver-examples#142]
Related to #62, we tried to implement the "autoposting" solr schema using the `create_cloud_development_environment` event with no luck.

On our pantheon.yml file we have this:
```
api_version: 1

workflows:
  create_cloud_development_environment:
    after:
      - type: webphp
        description: Enables Solr backend
        script: private/quicksilver-scripts/configure_solr.php
```

Then, we have the configure_solr.php file, that contains the next code:

```

<?php
// Prevent this script to be executed out of pantheon.
if (!defined('PANTHEON_ENVIRONMENT') || (PANTHEON_ENVIRONMENT === 'live')) {
  return;
}

// Bootstrap Drupal using the same technique as is in index.php.
define('DRUPAL_ROOT', $_SERVER['DOCUMENT_ROOT']);
require_once DRUPAL_ROOT . '/includes/bootstrap.inc';
drupal_bootstrap(DRUPAL_BOOTSTRAP_DATABASE);
$default_path = 'sites/all/modules/apachesolr/solr-conf/solr-3.x/schema.xml';
$schema_path = variable_get('pantheon_apachesolr_schema', $default_path);
pantheon_apachesolr_post_schema_exec($schema_path);
```

But this code is not working and I can not figure out why. Also, I tried to debug it following the steps mentioned in the troubleshooting part of the quicksilver documentation, it says to use `terminus workflow:list` to get the logs. I just created a new multidev environment and it does not even appear on the list of workflows, so is not possible to get the logs.
