### ISSUE TITLE
Bootstrapping drupal not working with Quicksilver?

### ISSUE THREAD

**Issue by danshumaker** [pantheon-systems/quicksilver-examples#18]
In this script: 

https://github.com/pantheon-systems/quicksilver-examples/blob/master/db_sanitization/db_sanitization_drupal.php

I have a simplified version which can not seem to bootstrap drupal.

```
<?php
echo "\n\n";
echo "\n========= START DB POST ===========\n";
if (defined('PANTHEON_ENVIRONMENT') && ($_ENV['PANTHEON_ENVIRONMENT'] !== 'live')) {
  echo "\nON PANTHEON\n";
  define('DRUPAL_ROOT', $_SERVER['DOCUMENT_ROOT']);
  require_once DRUPAL_ROOT . '/includes/bootstrap.inc';
  echo "\nBEFORE BOOTSTRAPPING\n";
  drupal_bootstrap(DRUPAL_BOOTSTRAP_DATABASE);
  echo "\nBOOTSTRAPPED DRUPAL\n";
} else {
  echo "\nNOT ON PANTHEON\n";
}
echo "\n========= END DB POST ===========\n";
echo "\n\n";
```

And line by line I commented stuff out to see where it fails.  Everything runs fine until after the line with the "BEFORE BOOSTRAPPING" message.   But when the next line executes it fails with this message:

```
PANTHEON ERROR:

Expected status 200, got: 301 while running your Quicksilver operation.

Please check your script path is correct and try again.
```

Has anyone gotten the Quicksilver system to successfully boostrap drupal?  If so how?

Thank you!

**Comment by Gfriedman21** [comment]
I fully bootstrapped Drupal in a similar fashion (https://github.com/pantheon-systems/quicksilver-examples/pull/13/files). I wonder what your server's file system looks like, as it seems that the call to $_SERVER['DOCUMENT_ROOT'] might not be providing what you expect it to. 

If that's not the issue, what does your pantheon.yml file look like?

**Comment by danshumaker** [comment]
My pantheon.yml file is in the drupal root as required.   I am able to run other quicksilver examples like after code syncs and database clones that post to slack.

I see in your example you bootstrap drupal to FULL and I was only bootstrapping to DATABASE, so I tried bootstrapping to FULL and that still didn't work.

here is my pantheon.yml file
```
api_version: 1

workflows:
  deploy:
    after:
      - type: webphp
        description: post to slack after each deploy
        script: private/scripts/slack_deploy_notification.php
  # Notify team of new commit to master
  sync_code:
    after:
      - type: webphp # we are told there will be more
        description: post to slack after each code pushed
        script: private/scripts/slack_sync_notification.php
  # Notify, sanitize,and notify on db clone
  clone_database:
    before:
      - type: webphp
        description: post to slack before cloning the database
        script: private/scripts/slack_before_db_clone.php
    after:
      - type: webphp
        description: Environment DEBUGGING
        script: private/scripts/debug.php
      - type: webphp
        description: Empty solr authorization
        script: private/scripts/solr_deauth_post_db_clone.php
```
