### ISSUE TITLE
Script path and 404 while running your Quicksilver operation

### ISSUE THREAD

**Issue by jigarius** [pantheon-systems/quicksilver-examples#182]
## The problem

- I followed the instructions on [this README](https://github.com/pantheon-systems/quicksilver-examples/tree/main/drush_config_import) and created a similar script.
  - I put my script under `web/private` and it didn't work.
  - I put it under `scripts/quicksilver/custom/drupal-deploy.php` and mentioned correctly in the `pantheon.yml` but it still didn't work
- The script doesn't work and the error message is not clear.
  - I get `404` while running your Quicksilver operation, but I'm not sure how I get a 404 if all I'm trying to do is run a script.
  - Also, since this is a script that is not to be accessed by the public, I wonder why the README suggests putting it inside `web/private` instead of `private/` or `scripts/`.

### Pantheon.yml

```yaml
workflows:
  sync_code:
    after:
      - type: webphp
        description: Run drush-deploy on test and live
        script: scripts/quicksilver/custom/drush-deploy.php
```

### drush-deploy.php

```php
<?php

// Do nothing if not on Pantheon test/live environments.
if (!in_array($_ENV['PANTHEON_ENVIRONMENT'], ['test', 'live'])) {
  return;
}

$commands = [
  'drush updatedb --no-cache-clear --yes',
  'drush cache:rebuild',
  'drush config:import --yes',
  'drush cache:rebuild',
  'drush config:import --yes',
  'drush cache:rebuild',
  'drush locale:check',
  'drush locale:update',
  'drush deploy:hook',
  'drush cache:rebuild',
];

foreach ($commands as $command) {
  echo "Running: $command" . PHP_EOL;
  passthru($command);
}
```

I wonder what's going on? What does _404 while running your Quicksilver operation_ mean?
